# Makefile for Docker development environment

# Automatically detect and export user information
export UID := $(shell id -u)
export GID := $(shell id -g)
export USR := $(shell whoami)
export PROJECT := hanbin_fm
export PROJECT_ROOT := /opt/project

.PHONY: env build up down restart shell clean help

# Default target
help:
	@echo "Available targets:"
	@echo "  env      - Create .env file with current user values"
	@echo "  build    - Build the Docker image"
	@echo "  up       - Start the container"
	@echo "  down     - Stop and remove the container"
	@echo "  restart  - Restart the container"
	@echo "  shell    - Open a shell in the running container"
	@echo "  clean    - Remove container and image"
	@echo "  help     - Show this help message"
	@echo ""
	@echo "Current user settings:"
	@echo "  UID=$(UID)"
	@echo "  GID=$(GID)"
	@echo "  USR=$(USR)"
	@echo "  PROJECT=$(PROJECT)"

# Create .env file with current user values
env:
	@echo "Creating .env file with current user values..."
	@echo "# Docker environment variables" > .env
	@echo "# Generated by 'make env' - modify as needed" >> .env
	@echo "" >> .env
	@echo "# User/Group IDs (automatically detected)" >> .env
	@echo "UID=$(UID)" >> .env
	@echo "GID=$(GID)" >> .env
	@echo "USR=$(USR)" >> .env
	@echo "" >> .env
	@echo "# Project configuration" >> .env
	@echo "PROJECT=$(PROJECT)" >> .env
	@echo "PROJECT_ROOT=$(PROJECT_ROOT)" >> .env
	@echo "" >> .env
	@echo ".env file created successfully!"
	@echo "Current settings: UID=$(UID), GID=$(GID), USR=$(USR)"

# Build the Docker image (automatically uses current user settings)
build:
	@echo "Building with UID=$(UID), GID=$(GID), USR=$(USR)"
	@docker-compose build

# Start the container
up:
	@echo "Starting container with UID=$(UID), GID=$(GID), USR=$(USR)"
	@docker-compose up -d

# Stop and remove the container
down:
	@docker-compose down

# Restart the container
restart: down up

# Open a shell in the running container
shell:
	@docker-compose exec irail /bin/bash

# Remove container and image
clean:
	@docker-compose down --rmi all --volumes --remove-orphans

# Force recreate .env file
env-force:
	@rm -f .env
	@$(MAKE) env

# Show current environment variables
show-env:
	@echo "Current environment variables:"
	@echo "UID=$(UID)"
	@echo "GID=$(GID)"
	@echo "USR=$(USR)"
	@echo "PROJECT=$(PROJECT)"
	@echo "PROJECT_ROOT=$(PROJECT_ROOT)" 